spring:
  application:
    name: web-management
  datasource:
    url: jdbc:mysql://localhost:3306/web_study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.wanna.webmanagement.pojo
  configuration:
    map-underscore-to-camel-case: true

